coverage:
  status:
    project:
      default:
        target: auto
        threshold: 20%
    patch:
      default:
        target: auto
        threshold: 20%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
